services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: Dkmf1rmt2!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build: ./Server
    container_name: backend
    ports:
      - "8080:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  app-network:

volumes:
  mssql_data:
